### ISSUE TITLE
Verify that IID are needed in the pheno file instead of platekeys

### ISSUE THREAD

**Issue by cgpu** [lifebit-ai/gel-gwas#25]
Ping @kousathanas for verifying this.

**Comment by cgpu** [comment]
This is resolved, cc' @kousathanas we know which platekeys  from each individual  are included in the aggregate vcf files(best quality sequencing run) and Filippo has the IDs.

**Comment by kousathanas** [comment]
IIDs in this context can be anything u want.
so IID=plate_key
