### ISSUE TITLE
Hardcoded sampleFile name in   step2_SPAtests.R 

### ISSUE THREAD

**Issue by cgpu** [lifebit-ai/gel-gwas#88]
https://github.com/lifebit-ai/gel-gwas/blob/2664c72dcbfb2a63c5d23ccd726d27c1f490d2ef/main.nf#L539

**Comment by mcamarad** [comment]
Thanks for pointing this @cgpu !!

This variable refers to: "Path to the file that contains one column for IDs of samples in the dosage file. For version >= 0.38, this file is only needed for bgen files". -> We use v. 0.39 of SAIGE

I will parametrize it, but as we don't use bgen files it won't be an issue or provoke one.

**Comment by evagradovich** [comment]
Resolved in https://github.com/lifebit-ai/gel-gwas/pull/105
