### ISSUE TITLE
Side by side comparison of gwas_filtering_bin vs gwas_filtering_qt: Why do we need 2 different processes?

### ISSUE THREAD

**Issue by cgpu** [lifebit-ai/gel-gwas#96]
https://github.com/lifebit-ai/gel-gwas/blob/bad3be8f516000a45e15602a6b2a4278c9421c2a/main.nf#L306-L317

**Comment by evagradovich** [comment]
Resolved in https://github.com/lifebit-ai/gel-gwas/pull/105
